### 주문번호 1번 주문 등록
POST {{host}}/api/v1/orders
Content-Type: application/json

{
  "orderLineItems": [
    {
      "productId": 1,
      "name": "신발A",
      "price": 15000
    },
    {
      "productId": 2,
      "name": "신발B",
      "price": 16000
    },
    {
      "productId": 3,
      "name": "신발C",
      "price": 17000
    }
  ]
}

### 주문번호 1번 - 신발A 교환 반품비 예상금액 조회
POST {{host}}/api/v1/orders/1/exchanges/calculate
Content-Type: application/json

{
  "returnLineItems": [
    {
      "lineItemId": 1
    }
  ]
}

### 주문번호 1번 - 신발A 교환 접수
POST {{host}}/api/v1/exchanges
Content-Type: application/json

{
  "orderId": 1,
  "reason": {
    "reason": "CHANGE_OF_MIND",
    "detailedReason": "상품 색상이 마음에 안들어요"
  },
  "returnShippingFee": 5000,
  "exchangeLineItems": [
    {
      "orderLineItemId": 1
    }
  ]
}

### 주문번호 1번 - 신발B 환불 반품비 예상금액 조회
POST {{host}}/api/v1/orders/1/refunds/calculate
Content-Type: application/json

{
  "returnLineItems": [
    {
      "lineItemId": 2
    }
  ]
}

### 주문번호 1번 - 신발B 환불 접수
POST {{host}}/api/v1/refunds
Content-Type: application/json

{
  "orderId": 2,
  "reason": {
    "reason": "CHANGE_OF_MIND",
    "detailedReason": "상품 색상이 마음에 안들어요"
  },
  "returnShippingFee": 2500,
  "refundLineItems": [
    {
      "orderLineItemId": 2
    }
  ]
}

### 주문번호 1번 - 신발C와 신발A' 한번에 환불 반품비 예상금액 조회
POST {{host}}/api/v1/orders/1/refunds/calculate
Content-Type: application/json

{
  "returnLineItems": [
    {
      "lineItemId": 3
    },
    {
      "lineItemId": 1
    }
  ]
}

### 주문번호 1번 - 신발C와 신발A' 한번에 환불 접수
POST {{host}}/api/v1/refunds
Content-Type: application/json

{
  "orderId": 2,
  "reason": {
    "reason": "CHANGE_OF_MIND",
    "detailedReason": "상품 색상이 마음에 안들어요"
  },
  "returnShippingFee": 2500,
  "refundLineItems": [
    {
      "orderLineItemId": 3
    },
    {
      "orderLineItemId": 1
    }
  ]
}